### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by accforgithubtest** [exaroth/liveboat#13]
This project looks neat, thank you for creating this.

Would you consider dockerizing this project ?
So it can be run in a "self-hosted" way instead of depending on github ?

**Comment by exaroth** [comment]
Ah, of course i can include dockerfile, the app itself is a single binary with no external dependencies (outside of Newsboat for fetching feed data) so dockerization should not be an issue. Will work something out later this week

**Comment by accforgithubtest** [comment]
Thank you, I look forward to being able to run this via docker,cheers !

**Comment by exaroth** [comment]
@accforgithubtest Here you go https://github.com/exaroth/liveboat/tree/develop/docker , had some free time this evening ;) Let me know if you have any issues running the image.

**Comment by accforgithubtest** [comment]
That is awesome, thank you so much !
Would you be willing to provide a official docker image for the project in ghcr / dockerhub / quay / etc ? (instead of end users having to build the project themselves). Users will then only have to provide the necessary config files, mounted as a volume via docker compose / run.

**Comment by exaroth** [comment]
Sure! Was about to push image to ghcr yesterday but run out of time , will add github action to push it automatically

**Comment by exaroth** [comment]
Liveboat is now available as ghcr image https://github.com/exaroth/liveboat/pkgs/container/liveboat, see README at https://github.com/exaroth/liveboat/blob/develop/docker/README.md for instructions on running it.

Cheers

**Comment by accforgithubtest** [comment]
Happy new year ! and Thank you so much for this! 

I tried to use the container with the below docker compose file, and keep getting the error in logs `Error: File or directory does not exist: '/liveboat/'`
```
services:
  liveboat:
    image: ghcr.io/exaroth/liveboat:latest
    container_name: liveboat
    volumes:
      - ./urls:/liveboat/urls
      - ./config.toml:/liveboat/config.toml
```

And I have just this in `urls` file
```
https://hnrss.org/frontpage?points=75 "~HN Front" dev
```

And this in `config.toml` file (same as default config file) -
```
name = "Default Template"
builder = "spa"
version = "1.0.4"
author = "Konrad Wasowicz (exaroth@gmail.com)"

[template_settings]
text-color = "#c7cfcc"
highlight-color = "#73bed3"
accent-color = "#2D4566"
background-color = "#121414"

```

Is there anything else I am missing ? Any suggestions on how to check the issue is appreciated.
I assume a newsboat installation is not a prerequisite ?

**Comment by exaroth** [comment]
Hi,
 the docker compose file looks good, tested it and it does run fine for me.

One obvious reason why it might be crashing is that you are using template config as liveboat config instead of actual global config file 
- `/liveboat/config.toml` defines global options for liveboat app - see reference [here](https://github.com/exaroth/liveboat?tab=readme-ov-file#options-file) - you can use https://github.com/exaroth/liveboat/blob/develop/docker/config.toml as example 
- The settings you linked above are per template options that define behaviour for that particular template (such as colors) - these are mounted in `/liveboat/templates/default/config.toml`

Could you try updating the docker compose  file as follows
```
services:
  liveboat:
    image: ghcr.io/exaroth/liveboat:latest
    container_name: liveboat
    volumes:
      - ./urls:/liveboat/urls
      - <PATH_TO_LIVEBOAT_CONFIG>:/liveboat/config.toml
      - <PATH_TO_TEMPLATE_CONFIG>:/liveboat/templates/default/config.toml
```
